In [1]:
import pandas as pd

In [12]:
data = pd.read_csv('../data/data_fixed_binary_values.csv')

In [13]:
pd.set_option("display.max_columns", None)

In [14]:
data

,Idade,num de ligações feitas,num dias desde a ultima ligação,previous,Taxa de Empregabilidade,Índice de Preços do consumidor,índice de confiança do consumidor,taxa euribor trimestral,Número de empregados,fez empréstimo ou não,Trabalho_admin.,Trabalho_blue-collar,Trabalho_entrepreneur,Trabalho_housemaid,Trabalho_management,Trabalho_retired,Trabalho_self-employed,Trabalho_services,Trabalho_student,Trabalho_technician,Trabalho_unemployed,Trabalho_unknown,Estado Civil_divorced,Estado Civil_married,Estado Civil_single,Estado Civil_unknown,Educação_basic.4y,Educação_basic.6y,Educação_basic.9y,Educação_high.school,Educação_illiterate,Educação_professional.course,Educação_university.degree,Educação_unknown,Crédito em incumprimento_no,Crédito em incumprimento_unknown,Crédito em incumprimento_yes,Financiamento imobiliário_no,Financiamento imobiliário_unknown,Financiamento imobiliário_yes,Empréstimo Pessoal_no,Empréstimo Pessoal_unknown,Empréstimo Pessoal_yes,Contato_cellular,Contato_telephone,mês_apr,mês_aug,mês_dec,mês_jul,mês_jun,mês_mar,mês_may,mês_nov,mês_oct,mês_sep,dia da semana_fri,dia da semana_mon,dia da semana_thu,dia da semana_tue,dia da semana_wed,resultado anterior_failure,resultado anterior_nonexistent,resultado anterior_success
0,56,1,999,0,1.1,93.994,-36.4,4.857,5191.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0
1,57,1,999,0,1.1,93.994,-36.4,4.857,5191.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0
2,37,1,999,0,1.1,93.994,-36.4,4.857,5191.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0
3,40,1,999,0,1.1,93.994,-36.4,4.857,5191.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0
4,56,1,999,0,1.1,93.994,-36.4,4.857,5191.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0
41184,46,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0
41185,56,2,999,0,-1.1,94.767,-50.8,1.028,4963.6,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0
41186,44,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0
41187,74,3,999,1,-1.1,94.767,-50.8,1.028,4963.6,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 63 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Idade                               41188 non-null  int64
 1   num de ligações feitas              41188 non-null  int64
 2   num dias desde a ultima ligação     41188 non-null  int64
 3   previous                            41188 non-null  int64
 4   Taxa de Empregabilidade             41188 non-null  float64
 5   Índice de Preços do consumidor      41188 non-null  float64
 6    índice de confiança do consumidor  41188 non-null  float64
 7   taxa euribor trimestral             41188 non-null  float64
 8   Número de empregados                41188 non-null  float64
 9   fez empréstimo ou não               41188 non-null  int64
 10  Trabalho_admin.                     41188 non-null  int64
 11  Trabalho_blue-collar                41188 non-null  int64
 12  Trabalho_entrepreneur               41188 non-null  int64
 13  Trabalho_housemaid                  41188 non-null  int64
 14  Trabalho_management                 41188 non-null  int64
 15  Trabalho_retired                    41188 non-null  int64
 16  Trabalho_self-employed              41188 non-null  int64
 17  Trabalho_services                   41188 non-null  int64
 18  Trabalho_student                    41188 non-null  int64
 19  Trabalho_technician                 41188 non-null  int64
 20  Trabalho_unemployed                 41188 non-null  int64
 21  Trabalho_unknown                    41188 non-null  int64
 22  Estado Civil_divorced               41188 non-null  int64
 23  Estado Civil_married                41188 non-null  int64
 24  Estado Civil_single                 41188 non-null  int64
 25  Estado Civil_unknown                41188 non-null  int64
 26  Educação_basic.4y                   41188 non-null  int64
 27  Educação_basic.6y                   41188 non-null  int64
 28  Educação_basic.9y                   41188 non-null  int64
 29  Educação_high.school                41188 non-null  int64
 30  Educação_illiterate                 41188 non-null  int64
 31  Educação_professional.course        41188 non-null  int64
 32  Educação_university.degree          41188 non-null  int64
 33  Educação_unknown                    41188 non-null  int64
 34  Crédito em incumprimento_no         41188 non-null  int64
 35  Crédito em incumprimento_unknown    41188 non-null  int64
 36  Crédito em incumprimento_yes        41188 non-null  int64
 37  Financiamento imobiliário_no        41188 non-null  int64
 38  Financiamento imobiliário_unknown   41188 non-null  int64
 39  Financiamento imobiliário_yes       41188 non-null  int64
 40  Empréstimo Pessoal_no               41188 non-null  int64
 41  Empréstimo Pessoal_unknown          41188 non-null  int64
 42  Empréstimo Pessoal_yes              41188 non-null  int64
 43  Contato_cellular                    41188 non-null  int64
 44  Contato_telephone                   41188 non-null  int64
 45  mês_apr                             41188 non-null  int64
 46  mês_aug                             41188 non-null  int64
 47  mês_dec                             41188 non-null  int64
 48  mês_jul                             41188 non-null  int64
 49  mês_jun                             41188 non-null  int64
 50  mês_mar                             41188 non-null  int64
 51  mês_may                             41188 non-null  int64
 52  mês_nov                             41188 non-null  int64
 53  mês_oct                             41188 non-null  int64
 54  mês_sep                             41188 non-null  int64
 55  dia da semana_fri                   41188 non-null  int64
 56  dia da semana_mon                   41188 non-null  int64
 57  dia da semana_thu                   41188 non-null  int64
 58  dia da semana_tue                   41188 non-null  int64
 59  dia da semana_wed                   41188 non-null  int64
 60  resultado anterior_failure          41188 non-null  int64
 61  resultado anterior_nonexistent      41188 non-null  int64
 62  resultado anterior_success          41188 non-null  int64
dtypes: float64(5), int64(58)
memory usage: 19.8 MB

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
import numpy as np

In [17]:
x = data[list(data.drop('fez empréstimo ou não', axis=1).columns)]
y = data['fez empréstimo ou não']

In [18]:
raw_treino_x, raw_teste_x, treino_y, teste_y = train_test_split(x, y, test_size= 0.25, stratify=y)
scaler = StandardScaler()
scaler.fit(raw_treino_x)
treino_x = scaler.transform(raw_treino_x)
teste_x = scaler.transform(raw_teste_x)

In [24]:
SEED = 5
np.random.seed(SEED)
print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))

trees = RandomForestClassifier(random_state = SEED, n_estimators=500, n_jobs=-1)
trees.fit(treino_x, treino_y)
previsoes = trees.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)

Treinaremos com 30891 elementos e testaremos com 10297 elementos
A acurácia foi 89.46%